export const getErrorText = (eventId) => {
  switch(eventId){
    case 2061 : return 'Browserul s-a închis până la terminarea autentificării.'
    case 2062 : return 'Parolă greșită sau cod de autentificare cu doi factori introdus.'
    case 2108 : return 'Depășește limita de extragere.'
    case 6511 : return 'Datele nu pot fi convertite în formatul ISO specificat.'
    case 10001 : return 'Banca emitentă a împiedicat tranzacția.'
    case 10003 : return 'Încălcarea securității (sursa nu este emitentul corect).'
    case 10004 : return 'Cardul a fost desemnat ca pierdut sau furat.'
    case 10005 : return 'Banca emitentă a refuzat tranzacția fără o explicație.'
    case 10006 : return 'Emitentul cardului a refuzat tranzacția deoarece există o problemă cu numărul cardului.'
    case 10012 : return 'Banca a refuzat tranzacția din cauza unui format sau câmp nevalid. Aceasta indică faptul că detaliile cardului sunt incorecte.'
    case 10013 : return 'Emitentul cardului a refuzat tranzacția din cauza unui format sau câmp nevalid.'
    case 10014 : return 'Emitentul cardului a refuzat tranzacția deoarece numărul cardului de credit este introdus incorect sau nu există.'
    case 10015 : return 'Emitentul cardului nu există.'
    case 10030 : return 'Emitentul cardului nu recunoaște detaliile tranzacției introduse. Acest lucru se datorează unei erori de format.'
    case 10041 : return 'Emitentul cardului a refuzat tranzacția, deoarece cardul a fost raportat pierdut.'
    case 10043 : return 'Cardul a fost desemnat ca pierdut sau furat.'
    case 10051 : return 'Cardul are fonduri insuficiente pentru a acoperi costul tranzacției.'
    case 10054 : return 'Gateway-ul de plată a refuzat tranzacția deoarece data de expirare a expirat sau nu se potrivește.'
    case 10055 : return 'PIN incorect.'
    case 10057 : return 'Emitentul cardului a refuzat tranzacția, deoarece cardul de credit nu poate fi utilizat pentru acest tip de tranzacție.'
    case 10058 : return 'Emitentul cardului a refuzat tranzacția, deoarece cardul de credit nu poate fi utilizat pentru acest tip de tranzacție.'
    case 10061 : return 'Depășește limita sumei de extragere.'
    case 10062 : return 'Banca clientului a refuzat cardul acestuia.'
    case 10063 : return 'Steagul a fost ridicat din cauza unei probleme de validare a securității.'
    case 10065 : return 'Emitentul solicită autentificarea puternică a clientului. Comerciantul ar trebui să reîncerce tranzacția după ce a autentificat cu succes clientul cu 3DS.'
    case 10070 : return 'Contactați emitentul cardului.'
    case 10075 : return 'Numărul permis de încercări PIN a fost depășit.'
    case 10076 : return 'Invalid / inexistent SAU Invalid / inexistent specificat.'
    case 10096 : return 'A apărut o eroare temporară în timpul tranzacției.'
    case 10200 : return 'A apărut o eroare temporară în timpul tranzacției.'
    case 10301 : return 'Emitentul solicită autentificarea puternică a clientului. Comerciantul ar trebui să reîncerce tranzacția după ce a autentificat cu succes clientul cu 3DS mai întâi.'
    default : return 'Eroare neidentificată'
  }
}